### ISSUE TITLE
Error when pushing the features to feature store

### ISSUE THREAD

**Issue by thak123** [airalcorn2/Solr-LTR#1]
when I execute the command for feature  

null:org.apache.solr.ltr.feature.FeatureException: tfidf_sim already contained in the store,&#8203; please use a different name
feature names are different in model and feature file 
Model-file:
 { "name" : "tfidf_sim_a" },
    { "name" : "tfidf_sim_b" },
    { "name" : "bm25_sim_a" },
    { "name" : "bm25_sim_b" },
    { "name" : "max_sim" }

feature-file:
 {
    "store" : "my_efi_feature_store",
    "name" : "tfidf_sim",
    "class" : "org.apache.solr.ltr.feature.SolrFeature",
    "params" : { "q" : "{!dismax qf=text_tfidf}${text_a}" }
  },
  {
    "store" : "my_efi_feature_store",
    "name" : "tfidf_sim",
    "class" : "org.apache.solr.ltr.feature.SolrFeature",
    "params" : { "q" : "{!dismax qf=text_tfidf}${text_b}" }
  },
  {
    "store" : "my_efi_feature_store",
    "name" : "bm25_sim",
    "class" : "org.apache.solr.ltr.feature.SolrFeature",
    "params" : { "q" : "{!dismax qf=text}${text_a}" }
  },
  {
    "store" : "my_efi_feature_store",
    "name" : "bm25_sim",
    "class" : "org.apache.solr.ltr.feature.SolrFeature",
    "params" : { "q" : "{!dismax qf=text}${text_b}" }
  },
  {
    "store" : "my_efi_feature_store",
    "name" : "max_sim",
    "class" : "org.apache.solr.ltr.feature.SolrFeature",
    "params" : { "q" : "{!dismax qf='text text_tfidf'}${text}" }
  }

**Comment by thak123** [comment]
I think changing the name of the features should fix the error

**Comment by airalcorn2** [comment]
You're right. I'll fix that. Thanks, @thak123.

**Comment by thak123** [comment]
hey  @airalcorn2 

http://localhost:8983/solr/test/query?q=historic north&rq={!ltr model=my_efi_model efi.text_a=historic efi.text_b=north efi.text='historic north'}&fl=id,score,[features]

this query returns no records unless I say query?q=text:historic north

Am I doing something wrong ?

**Comment by thak123** [comment]
Also this python code 
q_field_a = row["field_a"]).strip().lower()
q_field_b = row["field_b"]).strip().lower()
q_field_c = row["field_c"]).strip().lower()
q_field_d = row["field_d"]).strip().lower()

there is extra ending bracket at the end of the row["field_a"] is some code missin or the bracket is extra ?

**Comment by airalcorn2** [comment]
@thak123 - I get a single result using Solr 6.6.1.  And the extra bracket was a typo. I'll correct that, thanks.

**Comment by thak123** [comment]
I have a question,
from where does the variable row gets populated ?

**Comment by airalcorn2** [comment]
@thak123 - that code is mostly supposed to be a template showing how you would use data from a database (for example) to perform Solr LTR queries.
