### ISSUE TITLE
Why do we need to negate the output scores when inferencing?

### ISSUE THREAD

**Issue by Ekkalak-T** [airalcorn2/Solr-LTR#10]
First of all, I would like to thank you for writing such a great tutorial on how to build Ranknet but I have a question when we inference the model. 

`score_ranks = rankdata(-scores)`

Why do we need to negate the output scores before calculating the ranking? I have followed your tutorial on my dataset and found that it is necessary to negate the score to get the reasonable result. I still doubt the reason for doing that.

**Comment by airalcorn2** [comment]
Is it possible you were providing training pairs in the order of (less_relevant, more_relevant)? The model expects all training samples to be ordered (more_relevant, less_relevant). That's the only thing that comes to mind without being able to see your code.

**Comment by Ekkalak-T** [comment]
Thank you for the prompt response! I was using the same code but with a different dataset. I also prepared the same data format as your tutorial (more_relevant, less_relevant). 

According to your tutorial, I just want to know why do we need to negate the score (-score) before feeding into scipy.stats.rankdata function?

![image](https://user-images.githubusercontent.com/22044205/46415199-f1a06f80-c74e-11e8-9a2d-9d74e82929b1.png)

**Comment by airalcorn2** [comment]
Oooh, sorry. [`rankdata`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rankdata.html) ranks things in ascending order, but higher scores are better here.
