### ISSUE TITLE
Expected Map to create a new ManagedResource but received a java.util.ArrayList

### ISSUE THREAD

**Issue by asheetal** [airalcorn2/Solr-LTR#14]
Thanks for this simple to copy-paste instructions. When I PUT the my_efi_features.json. I get a error that I am unable to go past. Wondering if I have missed something obvious.

```
{
  "responseHeader":{
    "status":400,
    "QTime":1},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"Expected Map to create a new ManagedResource but received a java.util.ArrayList",
    "code":400},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"Expected Map to create a new ManagedResource but received a java.util.ArrayList",
    "code":400}}
```

**Comment by airalcorn2** [comment]
I didn't get this error on Solr 8.10.0. You're using the same `my_efi_features.json` included in the tutorial? Can you share the command you're using?

**Comment by asheetal** [comment]
Thanks for replying back. Using same solr 8.10.0 as welll. Here is the command I used on the same my_efi_features.json copied from your tutorial. 
```
curl -XPUT 'http://localhost:8983/solr/mytestcollection/schema/feature-store' --data-binary "@./my_efi_features.json" -H 'Content-type:application/json'
```

**Comment by airalcorn2** [comment]
Not sure, sorry. Maybe try starting over from scratch and using the same core name (i.e., `test`) so you can mostly copy and paste each step?

**Comment by asheetal** [comment]
Thanks. Seems that helped. The problem was in permissions. Since I am working in cloud, the folder write permissions and ability to create indexes was all messed up. Pulled everything in user space and now no more errors. Though it is not something I would leave unattended overnight. Now trying to make sense of the query and the results generated from query.

**Comment by nishit-rapidops** [comment]
Expected Map to create a new ManagedResource but received a java.util.ArrayList. Stilling get same error on Solr 9
