### ISSUE TITLE
Query regarding LTR plugin in solr

### ISSUE THREAD

**Issue by prateekagarwal95** [airalcorn2/Solr-LTR#3]
Hi, 

I'm working on ltr feature in solr and stuck with this problem on which i have spent considerable hours.
Can you help me out in this.

Problem:

**Output feature score before normalizing**

Doc_id     f1  f2  f3
Doc1:     2   50   10
Doc2:     2   0   10
Doc3:     2   100  10

**Output feature score after normalizing(which i want):**

_suppose i want to normalize onlt f2 feature between (0 to 50)_

Doc_id     f1  f2  f3
Doc1:     2   25   10
Doc2:     2   0   10
Doc3:     2   50  10

Somethhing which looks at the maximum from the returned set for that particular feature and change the scoring accordingly like some kind of custom Normalizer.

Can be please guide me like how to iterate over documents because from my understanding of source code it passes one document at a time in the custom normalizer class so will it really help writing a custom normalizer only??

If anything is unclear please let me know.

Thanks in advance

**Comment by airalcorn2** [comment]
I believe you want "[function queries](https://lucene.apache.org/solr/guide/6_6/function-queries.html)". Something like:

`"params":{"q": "{!func}div(f2, div(max(f2), 50))"}`

The `query` function allows you to chain together functions on subqueries.

**Comment by prateekagarwal95** [comment]
From what I understand you are suggesting to add this params during feature declartion in json but can we use something during normalization in model file??

Some kind of normalization class.

And the above method you recommended takes a lot of time and here:
`"params":{"q": "{!func}div(f2, div(max(f2), 50))"}` 50 is dynamic changes with different query so what to do??

Do you have any other suggestion??
