### ISSUE TITLE
LTR query

### ISSUE THREAD

**Issue by prateekagarwal95** [airalcorn2/Solr-LTR#4]
Regarding #3 
From what I understand you are suggesting to add this params during feature declartion in json but can we use something during normalization in model file??

Some kind of normalization class.

And the above method you recommended takes a lot of time and here:
"params":{"q": "{!func}div(f2, div(max(f2), 50))"} > 50 is dynamic and changes with different query so what to do??

Do you have any other suggestion??

**Comment by airalcorn2** [comment]
I do not, and this is not really the forum for these types of questions. You should try the [solr-user mailing list](http://lucene.apache.org/solr/community.html#mailing-lists-irc).
