### ISSUE TITLE
variables in python scripts are not defined

### ISSUE THREAD

**Issue by vvksingh24** [airalcorn2/Solr-LTR#5]
@airalcorn2  first of all thanks for such nice guide. But I am stuck in ranknet python scripts some variables are not defined  such as : 
`q_id = row["id"]

text_a = row["text_a"].strip().lower()

text_b = row["text_b"].strip().lower()`
and `if q_id in relevant.get(doc_id, {}):` i don't get it what is  row and  relevant for and  how to use them.
Thanks in Advance

**Comment by airalcorn2** [comment]
The included Python code is supposed to be a template, not run as is. `row` might be a row of data in a database table containing query text (and that text might be entered in several fields). `relevant` is a dictionary that maps a `doc_id` to a set of `q_id`s to which the `doc_id` is considered "relevant".
